##
## Docker Compose file for running tests
##

version: '3'

networks:
  internal:

services:

  database:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: db
      MYSQL_ROOT_PASSWORD: "unsafe"
      MYSQL_PASSWORD: "unsafe"
    networks:
      - internal

  backup:
    image: '${DOCKER_IMAGE:-oneofftech/database-backup-cron:main}'
    environment:
      DB_HOST: database
      DB_DATABASE: test
      DB_USER: db
      DB_PASSWORD: "unsafe"
      CRON_SCHEDULE: "* * * * *"
    depends_on:
      - database
    networks:
      - internal
    volumes: 
      - "/home/backup/backups"
