name: CI

on: 
  push:
    branches: 
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shellcheck:
    name: Check Shell scripts
    runs-on: ubuntu-latest
    container: 
      image: "koalaman/shellcheck-alpine:v0.7.2"
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Run Testsuite
      run: |
        shellcheck ./backup.sh
        shellcheck ./entrypoint.sh
